### ISSUE TITLE
I have found a problem, can you help me solve it?

### ISSUE THREAD

**Issue by Boye-Z** [IBM/adaptive-federated-learning#1]
I have found a problem, can you help me solve it?
For ：     
label = unpack('>B', f_labels.read(1))[0]
struct.error: unpack requires a buffer of 1 bytes

**Comment by li200005** [comment]
Excuse me, do you know how to run 5 parallel instances of client.py on the same machine as the server?

**Comment by shiqiangw** [comment]
> I have found a problem, can you help me solve it? For ： label = unpack('>B', f_labels.read(1))[0] struct.error: unpack requires a buffer of 1 bytes

I'm not sure, but it's possible that you didn't put the data in the correct location.

**Comment by li200005** [comment]
Thanks. I‘ve run it successfully. Considering that there may still be questions about this paper in the future, is it possible to add a friend?

**Comment by Boye-Z** [comment]
> 

Sure,I would be more than happy to discuss with you
