### ISSUE TITLE
Run 5 parallel instances of client.py on the same machine as the server

### ISSUE THREAD

**Issue by li200005** [IBM/adaptive-federated-learning#2]
I don't know how to run 5 parallel instances of client.py on the same machine as the server.
I've tried multithreading and multi-process, but still stuck at this step "Waiting for incoming connections...".
Could you please teach me how to do this?

**Comment by shiqiangw** [comment]
The easiest way to test this is to open 5 different terminals and run one client instance in each terminal. The server can run in separate terminal as well. Running multiple processes in the background should work too, if implemented correctly.

**Comment by li200005** [comment]
> 

Thanks. I‘ve run it successfully. Considering that there may still be questions about this paper in the future, is it possible to add a friend?
