### ISSUE TITLE
自适应联邦学习

### ISSUE THREAD

**Issue by li200005** [IBM/adaptive-federated-learning#3]
您好！我在拜读您这篇论文时有些地方感到不解，虽然您的标题是基于资源受限边缘计算系统下的自适应联邦学习，但我感觉你的模型构造并不是基于边缘计算系统。
![image](https://user-images.githubusercontent.com/58905357/161667952-41fc38ae-c32a-4a3f-ab92-c0c0aa9df838.png)
我理解中的基于边缘计算系统的联邦学习应如上图有边缘聚合和全局聚合，但您的算法2和算法3中只有节点和聚合，这更像是联邦学习的经典模型。能否请您分享一下您当时是怎么思考的？又或者能不能麻烦您指出我理解上的问题？

**Comment by li200005** [comment]
I see that your name is like a Chinese and uses Chinese, if you need to use English, please say it

**Comment by shiqiangw** [comment]
Please only post code-related questions as issues. If you have other questions, send me an email.
