### ISSUE TITLE
Help to change this repository!

### ISSUE THREAD

**Issue by sankopay** [IBM/adaptive-federated-learning#4]
Hello there!
I’m writing to you regarding a github repository you have made, which is of interest to me. 
The repository I’m talking about is the current one and I’m doing a project which consists of this one”https://github.com/qub-blesson/FedAdapt" but i made some changes to yours like i wanted to run it for 3 virtual machines (windows 10) with 1Gb of Ram, 20Gb of hard disk, and this project is so important to me, but i wanted to only use SVM and CNN with stochastic gradient descent and the dataset is also just MNIST dataset. So now i want to use and add the part where you have done the online cloud offloading.

So would you please please please help me merge your code with the later repository for the offloading part? and also is it possible to do all that in python or jupyter notebook? i really am so desperate please please help a student in need, I know you must be so busy but i’m so mentally down that i can’t function well and the deadline for this project is approaching please help me merge the offloading part of your project with my customized project with the mentioned features above. it’s the exact federated learning with resource-constrained algorithms but it need the offloading part which i cant wrap up my mind around it.

**Comment by shiqiangw** [comment]
Sorry, but I don’t know what you mean by “offloading part”. I don’t think this is a valid issue so I’ll close it. Feel free to send me an email if you have specific questions.
